# -*- coding: utf-8 -*-
"""voiceclone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16a7d5MWzj7TNo6iw5gtRf4cgc_QTML6s
"""

!pip install -q yt-dlp
!apt-get -qq install -y ffmpeg

!pip install -q yt-dlp
!apt-get -qq install -y ffmpeg
import subprocess
from pathlib import Path

def download_youtube_audio(youtube_url, output_filename="output.wav"):
    temp_file = "temp_audio.%(ext)s"

    print("📥 Downloading audio...")
    subprocess.run([
        "yt-dlp",
        "-x", "--audio-format", "wav",
        "-o", temp_file,
        youtube_url
    ], check=True)

    # Find the downloaded file
    downloaded_file = None
    for file in Path(".").glob("temp_audio.*"):
        downloaded_file = str(file)
        break

    if not downloaded_file:
        raise FileNotFoundError("❌ Audio file not found.")

    print("🎧 Converting to WAV (16kHz mono)...")
    subprocess.run([
        "ffmpeg", "-y",
        "-i", downloaded_file,
        "-ar", "16000",
        "-ac", "1",
        output_filename
    ], check=True)

    Path(downloaded_file).unlink()
    print(f"✅ Done! Audio saved as: {output_filename}")
youtube_url = input("Enter YouTube video URL: ")
download_youtube_audio(youtube_url)

!pip install -q yt-dlp
!apt-get -qq install -y ffmpeg
import subprocess
from pathlib import Path

def download_youtube_audio(youtube_url, output_filename="output.wav"):
    temp_file = "temp_audio.%(ext)s"

    try:
        print("📥 Downloading audio...")
        subprocess.run([
            "yt-dlp",
            "-x", "--audio-format", "wav",
            "-o", temp_file,
            youtube_url
        ], check=True)
    except subprocess.CalledProcessError:
        print("❌ Error: Failed to download the video/audio. Please check the URL and try again.")
        return

    # Find the downloaded file
    downloaded_file = None
    for file in Path(".").glob("temp_audio.*"):
        downloaded_file = str(file)
        break

    if not downloaded_file:
        print("❌ Audio file not found.")
        return

    print("🎧 Converting to WAV (16kHz mono)...")
    try:
        subprocess.run([
            "ffmpeg", "-y",
            "-i", downloaded_file,
            "-ar", "16000",
            "-ac", "1",
            output_filename
        ], check=True)
    except subprocess.CalledProcessError:
        print("❌ Error: Failed to convert the audio. Please try again.")
        return

    Path(downloaded_file).unlink()  # Clean up temporary file
    print(f"✅ Done! Audio saved as: {output_filename}")

    # If you're using Jupyter or Colab, you can download the file using:
    try:
        from google.colab import files
        files.download(output_filename)  # This is for Colab
    except ImportError:
        # For local usage, just inform the user where the file is saved
        print(f"✅ The audio has been saved locally as {output_filename}")

# Get user input (for local use)
youtube_url = input("Enter YouTube video URL: ").strip()
if youtube_url:
    download_youtube_audio(youtube_url)
else:
    print("⚠️ Please provide a valid YouTube URL.")